{% set name = "plantcv" %}
{% set version = "3.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c842855c7558463a971d02db47e430d62001e2aad7da559c7f6d2f27ca3026e5
  patches:
    - 0001-Patch-requirements-and-setup.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=1.5
    - numpy >=1.11
    - opencv <4,>=3.4
    - pandas
    - plotnine
    - python
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy
    - dask
    - dask-jobqueue

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://plantcv.danforthcenter.org
  summary: An image processing package for plant phenotyping.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
