{% set name = "plantcv" %}
{% set version = "4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9084861d5a5725f1a92b516fdfb7a198f7b3bf7c7714bfefef907cd778ff8473
  patches:
    - 0001-Patch-pyproject.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=1.5
    - numpy >=1.11
    - opencv
    - pandas
    - python >=3.6
    - python-dateutil
    - scikit-image >=0.19
    - scikit-learn
    - scipy
    - dask
    - dask-jobqueue
    - statsmodels
    - xarray >=2022.11.0
    - altair
    - vl-convert-python

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - pip
    - libopencv *=headless*

about:
  home: https://plantcv.org
  dev_url: https://github.com/danforthcenter/plantcv
  doc_url: https://plantcv.readthedocs.io
  summary: An image processing package for plant phenotyping.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
