{% set name = "plantcv" %}
{% set version = "3.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 76d39e55c7c19595b4d12f1c04672f6add69c6f45d470fadf3320b07b8ade4af
  patches:
    - 0001-Patch-requirements-and-setup.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - matplotlib-base >=1.5
    - numpy >=1.11
    - opencv <4,>=3.4
    - pandas
    - plotnine
    - python
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://plantcv.danforthcenter.org
  summary: An image processing package for plant phenotyping.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
