{% set name = "plantcv" %}
{% set version = "4.10.2" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 708db985903de0a64b6d83cc01600af50964ad6ed2c32a3ee03f41d243f549d2
  patches:
    - 0001-Patch-pyproject.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation

requirements:
  host:
    - setuptools
    - setuptools_scm
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base >=1.5
    - numpy >=1.26
    - opencv
    - pandas
    - python >={{ python_min }}
    - python-dateutil
    - scikit-image >=0.19
    - scikit-learn
    - scipy
    - dask
    - dask-jobqueue
    - statsmodels
    - xarray >=2022.11.0
    - altair <6
    - vl-convert-python
    - nd2
    - flyr

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - libopencv *=headless*

about:
  home: https://plantcv.org
  dev_url: https://github.com/danforthcenter/plantcv
  doc_url: https://plantcv.readthedocs.io
  summary: An image processing package for plant phenotyping.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
