{% set name = "plantcv" %}
{% set version = "4.7" %}
{% set python_min = "3.9" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 44405e114ab2e8337f47d85957a6541157f4a3dab2ec158d3c75650b0a8be23f
  patches:
    - 0001-Patch-pyproject.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - setuptools
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base >=1.5
    - numpy >=2
    - opencv
    - pandas
    - python >={{ python_min }}
    - python-dateutil
    - scikit-image >=0.19
    - scikit-learn
    - scipy
    - dask
    - dask-jobqueue
    - statsmodels
    - xarray >=2022.11.0
    - altair
    - vl-convert-python

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip
    - libopencv *=headless*

about:
  home: https://plantcv.org
  dev_url: https://github.com/danforthcenter/plantcv
  doc_url: https://plantcv.readthedocs.io
  summary: An image processing package for plant phenotyping.
  license: MPL-2.0
  license_family: MOZILLA
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
