{% set name = "plantcv" %}
{% set version = "3.14" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ccd4f755543935eb6d26f5bc1189a986218f0c64a708b328d26071411c1350ba
  patches:
    - 0001-Patch-requirements-and-setup.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base >=1.5
    - numpy >=1.11
    - opencv
    - pandas
    - plotnine
    - python >=3.6
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy
    - dask
    - dask-jobqueue
    - statsmodels

test:
  imports:
    - plantcv
    - plantcv.learn
    - plantcv.parallel
    - plantcv.utils
    - plantcv.plantcv
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://plantcv.danforthcenter.org
  summary: An image processing package for plant phenotyping.
  license: MIT
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nfahlgren
